export const PARSE_DESKTOP_URL_START = 'PARSE_DESKTOP_URL_START';
export const PARSE_DESKTOP_URL_SUCCESS = 'PARSE_DESKTOP_URL_SUCCESS';
export const PARSE_DESKTOP_URL_FAILURE = 'PARSE_DESKTOP_URL_FAILURE';