export const SET_PLAYER_HEALTH = 'SET_PLAYER_HEALTH';
export const SET_MONSTER_HEALTH = 'SET_MONSTER_HEALTH';

export const SET_PLAYER_ATTACK = 'SET_PLAYER_ATTACK';
export const SET_MONSTER_ATTACK = 'SET_MONSTER_ATTACK';

export const SET_PLAYER_CHARACTER_CODE = 'SET_PLAYER_CHARACTER_CODE';
