export const PLAYER_ROLLING_DICE_START = 'PLAYER_ROLLING_DICE_START';
export const PLAYER_ROLLING_DICE_FINISH = 'PLAYER_ROLLING_DICE_FINISH';
export const MONSTER_ROLLING_DICE_START = 'MONSTER_ROLLING_DICE_START';
export const MONSTER_ROLLING_DICE_FINISH = 'MONSTER_ROLLING_DICE_FINISH';
export const DISPLAY_PLAYER_TOTAL_SCORE = 'DISPLAY_PLAYER_TOTAL_SCORE';
export const DISPLAY_MONSTER_TOTAL_SCORE = 'DISPLAY_MONSTER_TOTAL_SCORE';