export const SET_BRANDSCHEME = 'SET_BRANDSCHEME';
export const TOGGLE_DROPDOWNOPEN_ID = 'TOGGLE_DROPDOWNOPEN_ID';
export const TOGGLE_DROPDOWNOPEN_CALLCONTEXT = 'TOGGLE_DROPDOWNOPEN_CALLCONTEXT';
export const TOGGLE_DROPDOWNOPEN_VERIFICATION = 'TOGGLE_DROPDOWNOPEN_VERIFICATION';
export const SET_ALLDROPDOWNOPEN_FALSE = 'SET_ALLDROPDOWNOPEN_FALSE';
export const SET_VISIBLE_IFRAME_APP = 'SET_VISIBLE_IFRAME_APP';
export const TOGGLE_LAUNCHER = 'TOGGLE_LAUNCHER';