export const DISPLAY_ATTACK_TEXT = 'DISPLAY_ATTACK_TEXT';
export const DISPLAY_ATTACK_BUTTON = 'DISPLAY_ATTACK_BUTTON';
export const DISPLAY_ATTACK_EFFECT = 'DISPLAY_ATTACK_EFFECT';
export const SCALE_HEALTH_BAR='SCALE_HEALTH_BAR';
