export const START_GAME_PROCESS = 'START_GAME_PROCESS';

export const START_ROLLING_DICE_PROCESS = 'START_ROLLING_DICE_PROCESS';

export const START_UPDATE_HEALTH_PROCESS = 'START_UPDATE_HEALTH_PROCESS';

