export const DISPATCH_TOAST_ERROR = 'DISPATCH_TOAST_ERROR';
export const DISPATCH_TOAST_WARN = 'DISPATCH_TOAST_WARN';
export const DISPATCH_TOAST_INFO = 'DISPATCH_TOAST_INFO';
export const DISPATCH_TOAST_SUCCESS = 'DISPATCH_TOAST_SUCCESS';